-- MySQL Script generated by MySQL Workbench
-- Tue Mar  7 02:45:19 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Hotel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Hotel` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Hotel` (
  `idHotel` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `adresse` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  PRIMARY KEY (`idHotel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Etage`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Etage` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Etage` (
  `numero` INT NOT NULL,
  `nombreChambre` VARCHAR(45) NULL,
  `Hotel_idHotel` INT NOT NULL,
  PRIMARY KEY (`numero`, `Hotel_idHotel`),
  INDEX `fk_Etage_Hotel_idx` (`Hotel_idHotel` ASC) VISIBLE,
  CONSTRAINT `fk_Etage_Hotel`
    FOREIGN KEY (`Hotel_idHotel`)
    REFERENCES `mydb`.`Hotel` (`idHotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hotel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Hotel` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Hotel` (
  `idHotel` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `adresse` VARCHAR(45) NULL,
  `telephone` VARCHAR(45) NULL,
  PRIMARY KEY (`idHotel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Client` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `idClient` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `prenom` VARCHAR(45) NULL,
  `telephone` INT NULL,
  `dateReserv` DATE NULL,
  `dateEntrer` DATE NULL,
  `dateSortie` DATE NULL,
  `nuite` INT NULL,
  `Hotel_idHotel` INT NOT NULL,
  PRIMARY KEY (`idClient`),
  INDEX `fk_Client_Hotel1_idx` (`Hotel_idHotel` ASC) VISIBLE,
  CONSTRAINT `fk_Client_Hotel1`
    FOREIGN KEY (`Hotel_idHotel`)
    REFERENCES `mydb`.`Hotel` (`idHotel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ServiceAnnexe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ServiceAnnexe` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ServiceAnnexe` (
  `idServiceAnnexe` INT NOT NULL,
  `nom` VARCHAR(45) NULL,
  `tarif` FLOAT NULL,
  `Client_idClient` INT NOT NULL,
  PRIMARY KEY (`Client_idClient`),
  CONSTRAINT `fk_ServiceAnnexe_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `mydb`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categorie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Categorie` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Categorie` (
  `idCategorie` INT NOT NULL,
  `classe` VARCHAR(45) NULL,
  `tarifNormal` FLOAT NULL,
  `tarifSpecial` FLOAT NULL,
  PRIMARY KEY (`idCategorie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Chambre`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Chambre` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Chambre` (
  `numero` VARCHAR(45) NOT NULL,
  `etat` VARCHAR(45) NULL,
  `Etage_numero` INT NOT NULL,
  `Categorie_idCategorie` INT NOT NULL,
  PRIMARY KEY (`numero`, `Etage_numero`, `Categorie_idCategorie`),
  INDEX `fk_Chambre_Etage1_idx` (`Etage_numero` ASC) VISIBLE,
  INDEX `fk_Chambre_Categorie1_idx` (`Categorie_idCategorie` ASC) VISIBLE,
  CONSTRAINT `fk_Chambre_Etage1`
    FOREIGN KEY (`Etage_numero`)
    REFERENCES `mydb`.`Etage` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Chambre_Categorie1`
    FOREIGN KEY (`Categorie_idCategorie`)
    REFERENCES `mydb`.`Categorie` (`idCategorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Reservation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Reservation` (
  `Client_idClient` INT NOT NULL,
  `Chambre_numero` VARCHAR(45) NOT NULL,
  `facture` FLOAT NULL,
  PRIMARY KEY (`Client_idClient`, `Chambre_numero`),
  INDEX `fk_Client_has_Chambre_Chambre1_idx` (`Chambre_numero` ASC) VISIBLE,
  INDEX `fk_Client_has_Chambre_Client1_idx` (`Client_idClient` ASC) VISIBLE,
  CONSTRAINT `fk_Client_has_Chambre_Client1`
    FOREIGN KEY (`Client_idClient`)
    REFERENCES `mydb`.`Client` (`idClient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Client_has_Chambre_Chambre1`
    FOREIGN KEY (`Chambre_numero`)
    REFERENCES `mydb`.`Chambre` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
